<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="1.238" timestamp="2024-10-22T05:17:06.476461+00:00" hostname="fv-az2031-287"><testcase classname="" name="tests.test_docs" time="0.000"><error message="collection failure">tests/test_docs.py:2: in &lt;module&gt;
    from main import app
app/main.py:8: in &lt;module&gt;
    from app.database import models
app/database/models.py:3: in &lt;module&gt;
    from app.database.connection import Base
app/database/connection.py:14: in &lt;module&gt;
    SQLALCHEMY_DATABASE_URL = config["DATABASE_URL"]
E   KeyError: 'DATABASE_URL'</error></testcase></testsuite></testsuites>